/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.sample.model.StudentAddress;
import com.liferay.sample.service.StudentAddressLocalServiceUtil;

/**
 * The extended model base implementation for the StudentAddress service. Represents a row in the &quot;student_address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentAddressImpl}.
 * </p>
 *
 * @author admin
 * @see StudentAddressImpl
 * @see com.liferay.sample.model.StudentAddress
 * @generated
 */
public abstract class StudentAddressBaseImpl extends StudentAddressModelImpl
	implements StudentAddress {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a student address model instance should use the {@link StudentAddress} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			StudentAddressLocalServiceUtil.addStudentAddress(this);
		}
		else {
			StudentAddressLocalServiceUtil.updateStudentAddress(this);
		}
	}
}