/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StudentAddress service. Represents a row in the &quot;student_address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.StudentAddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.StudentAddressImpl}.
 * </p>
 *
 * @author admin
 * @see StudentAddress
 * @see com.liferay.sample.model.impl.StudentAddressImpl
 * @see com.liferay.sample.model.impl.StudentAddressModelImpl
 * @generated
 */
public interface StudentAddressModel extends BaseModel<StudentAddress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student address model instance should use the {@link StudentAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this student address.
	 *
	 * @return the primary key of this student address
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this student address.
	 *
	 * @param primaryKey the primary key of this student address
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the address ID of this student address.
	 *
	 * @return the address ID of this student address
	 */
	public int getAddressId();

	/**
	 * Sets the address ID of this student address.
	 *
	 * @param addressId the address ID of this student address
	 */
	public void setAddressId(int addressId);

	/**
	 * Returns the city of this student address.
	 *
	 * @return the city of this student address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this student address.
	 *
	 * @param city the city of this student address
	 */
	public void setCity(String city);

	/**
	 * Returns the country of this student address.
	 *
	 * @return the country of this student address
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this student address.
	 *
	 * @param country the country of this student address
	 */
	public void setCountry(String country);

	/**
	 * Returns the sid of this student address.
	 *
	 * @return the sid of this student address
	 */
	public int getSid();

	/**
	 * Sets the sid of this student address.
	 *
	 * @param sid the sid of this student address
	 */
	public void setSid(int sid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StudentAddress studentAddress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StudentAddress> toCacheModel();

	@Override
	public StudentAddress toEscapedModel();

	@Override
	public StudentAddress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}